# 메인 파일 이름을 지정하세요.
main_file = 'project.py'

# 데이타 파일들을 지정하세요.
data_files = [
    'beer.png','bgm.wav','bottle_break.wav','cure.png','ENCR10B.TTF','gameclear.png','gameover.png'
    ,'gun.png','gunsound.wav','healpack.wav','heart.png','map.jpg','reload.wav','startscreen.png','stage_clear.png','gun_sprite.png'
    ,'scope.png'
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
    # fill here
]

